FROM php:apache

USER root

RUN apt update && apt-get -y install git

# check out i2b2-webclient
WORKDIR /opt
RUN git clone https://github.com/i2b2/i2b2-webclient.git

# DEVELOPER VERSION, WILL CONNECT TO DOCKER HOST
WORKDIR /opt/i2b2-webclient
COPY i2b2_config_data_develop.js i2b2_config_data.js
COPY index_develop.php index.php

# copy to apache web folder
RUN cp -r * /var/www/html
